%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 0          
num_of_cam: 2  

imu_topic: "/camera/imu"
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"
output_path: "/data/output/vins_fusion"

cam0_calib: "d435i_infra1.yaml"
cam1_calib: "d435i_infra2.yaml"
image_width: 640
image_height: 480


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99994207, -0.0004406,  -0.0107543,  -0.01146189,
                0.00040811,  0.99999535, -0.00302324, -0.00687172,
                0.01075559,  0.00301868,  0.9999376,  -0.05204526,
                0.,          0.,          0.,          1.        ]
  

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0.99997245,  0.00055232,  0.00740214,  0.06114153,
          -0.00056978,  0.99999706,  0.00235798,  0.00697592,
           0.00740082, -0.00236214,  0.99996982,  0.05133192,
           0.,          0.,          0.,          1.        ]

#Multiple thread support
multiple_thread: 4

#feature traker paprameters
max_cnt: 120            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.05668127670508405          # accelerometer measurement noise standard deviation. 
gyr_n: 0.002793095523064431         # gyroscope measurement noise standard deviation.     
acc_w: 0.0010914773159861363        # accelerometer bias random work noise standard deviation.  
gyr_w: 2.7571476732540106e-05       # gyroscope bias random work noise standard deviation.     
g_norm: 9.80636452     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.000859232396824                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/data/output/vins_fusion/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
